In [41]:
import tkinter as tk
from PIL import ImageTk,Image,ImageDraw
from matplotlib import pyplot as plt
#pip install pillow

import numpy as np
import cv2
import joblib

width=500
height=500

font_btn='Helvetica 20 bold'
font_label='Helvetica 24 bold'

count=0

model=joblib.load('KNN-Handwritten-Written-Digits.sav')

def event_function(event):
    
    x=event.x
    y=event.y
    
    x1=x-30
    x2=x+30
    y1=y-30
    y2=y+30
    
    canvas.create_oval((x1,y1,x2,y2),fill='black')
    img_draw.ellipse((x1,y1,x2,y2),fill='white')
    
def save():
    
    global count
    
    img_array=np.array(img)
    cv2.imwrite('sample-'+str(count)+'.jpg',img_array)
    
    count=count+1
    
def clear():
    
    global img,img_draw

    canvas.delete('all')
    img=Image.new('RGB',(width,height),(0,0,0))
    img_draw=ImageDraw.Draw(img)
    
    label_status.config(text='PREDICTED DIGIT: NONE')
    
def predict():
    
    img_array=np.array(img)
    img_array=cv2.cvtColor(img_array,cv2.COLOR_BGR2GRAY)
    img_array=cv2.resize(img_array,(8,8))
    
    print(img_array)
    
    img_array=(img_array/255)*15
    
    print(img_array)
    
    img_array=img_array.reshape(1,64)
    
    result=model.predict(img_array)
    
    label_status.config(text='PREDICTED DIGIT: '+str(result))
    
window=tk.Tk()

canvas=tk.Canvas(window,width=width,height=height,bg='white')
canvas.grid(row=0,column=0,columnspan=4)

button_save=tk.Button(window,text="SAVE",bg='green',fg='white',font=font_btn,command=save)
button_save.grid(row=1,column=0)

button_predict=tk.Button(window,text="PREDICT",bg='blue',fg='white',font=font_btn,command=predict)
button_predict.grid(row=1,column=1)

button_clear=tk.Button(window,text="CLEAR",bg='yellow',fg='white',font=font_btn,command=clear)
button_clear.grid(row=1,column=2)

button_exit=tk.Button(window,text="EXIT",bg='red',fg='white',font=font_btn,command=window.destroy)
button_exit.grid(row=1,column=3)

label_status=tk.Label(window,text='PREDICTED DIGIT: NONE',bg='white',font=font_label)
label_status.grid(row=2,column=0,columnspan=4)

canvas.bind('<B1-Motion>',event_function)

img=Image.new('RGB',(width,height),(0,0,0))
img_draw=ImageDraw.Draw(img)

window.mainloop()

[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0 255 255   0   0]
 [  0   0   0   0   0   0 255   0]
 [  0   0   0   0 255 255   0   0]
 [  0   0   0   0 255 255 255   0]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 15. 15.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0. 15. 15.  0.  0.]
 [ 0.  0.  0.  0. 15. 15. 15.  0.]]
[[  0   0   0 255 255   0   0   0]
 [  0 255 255   0   0 255   0   0]
 [  0 255   0   0   0 255   0   0]
 [  0   0   0   0   0 255   0   0]
 [  0   0   0 255 255   0   0   0]
 [  0 255 255   0   0   0   0   0]
 [  0 255 255 255 255 255 255   0]
 [  0   0   0   0   0   0   0   0]]
[[ 0.  0.  0. 15. 15.  0.  0.  0.]
 [ 0. 15. 15.  0.  0. 15.  0.  0.]
 [ 0. 15.  0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0. 15.